backup_type: incremental
compress: true
exclude_dirs:
- data
schedule: 0 2 * * *
source_dir: ./test
split_size_mb: 1024
target:
  password: pass
  path: ./test-bk
  type: local
  url: https://webdav.example.com/backup
  username: user
